name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  linux:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Update version
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install cmake`
    - name: Build project
      run: make

  macos:

    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Update version
      run: brew update
    - name: Install Dependencies
      run: brew install cmake
    - name: Build project
      run: make
